# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Abate
tagline:          'Robotics Engineer'
description:      'A.'
baseurl:          /

author:
  name:           'Abate De Mey'
  url:            https://www.linkedin.com/in/abate-de-mey/

paginate:         3
paginate_path:   "/robohub_posts/page:num/"

# Custom vars
version:          2.1.0

plugins:          [jekyll-paginate]
